[package]
name = "stable-hash"
version = "0.4.0"
authors = ["Zac Burns <That3Percent@gmail.com>"]
edition = "2018"


[dependencies]
blake3 = "0.3.3"
num-traits = "0.2.11"
leb128 = "0.2.4"
ibig = "0.3.1"
lazy_static = "1.4.0"
firestorm = "0.4.6" 

[dev-dependencies]
twox-hash = "1.5.0"
hex = "0.4.2"
rand = "0.8.4"
